jobs:
  run:
    name: Run
    runs-on: ubuntu-20.04

    steps:
      - name: Start Up
        uses: actions/checkout@v2
      - name: Install Packages
        run: sudo apt-get update && sudo apt-get install -y libhwloc15 unrar
      - name: Run Tests
        run: ./build/test

name: Check

on:
  schedule:
    - cron: "25 1/3 * * *"
